{"uuid": "b3510e49-a448-4e1f-b1c6-f8d13a7e108d", "children": ["aa07febc-921c-47d8-be7e-59d283407c28"], "befores": [{"name": "app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost/addressbook/&c=UTF-8&d=Firefox%20%D0%BD%D0%B5%20%D0%BC%D0%BE%D0%B6%D0%B5%D1%82%20%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C%20%D1%81%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5%20%D1%81%20%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%BE%D0%BC%20localhost.\nStacktrace:\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.jsm:510:5\ncheckReadyState@chrome://remote/content/marionette/navigate.js:64:24\nonNavigation@chrome://remote/content/marionette/navigate.js:312:39\nemit@resource://gre/modules/EventEmitter.jsm:160:20\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.jsm:44:25\n\n", "trace": "  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\conftest.py\", line 34, in app\n    fixture.session.ensure_login(username=web_config['username'], password=web_config['password'])\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\fixture\\session.py\", line 47, in ensure_login\n    self.login(username, password)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\fixture\\session.py\", line 8, in login\n    self.app.open_home_page()\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\fixture\\application.py\", line 34, in open_home_page\n    wd.get(self.base_url)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 437, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1651092916661, "stop": 1651092929455}], "start": 1651092916661, "stop": 1651092930311}